### ISSUE TITLE
version 0.7 won't compile

### ISSUE THREAD

**Issue by AntoineRenaud91** [mthh/sfcgal-rs#3]
Dear maintainers,

First, thank you for this useful crate! After upgrading to 0.7, I noticed the crate does not compile anymore as some APIs seem to be missing from the sfcgal-sys crate, namely *sfcgal_geometry_extrude_polygon_straight_skeleton* and *sfcgal_geometry_extrude_straight_skeleton*.

Kind regards

**Comment by mthh** [comment]
Hi and thanks for your feedback,

The sfcgal-sys v0.7 crate (and therefore the sfcgal v0.7 crate) expects to find SFCGAL version 1.5.x on your machine (which exports these two new functions), so I guess you are trying to use it against SFCGAL 1.4.x ?

The addition of the two functions you mention is the main change between versions 0.6 and 0.7, so if you want to continue using SFCGAL 1.4.x you can stay with the sfcgal v0.6 crate.

I need to manage this aspect better in future versions so that the version of sfcgal-sys / sfcgal-rs is not so strongly linked to a version of SFCGAL (and so that users can use new versions of the crates while continuing to link them to the same version of SFCGAL).

**Comment by AntoineRenaud91** [comment]
thanks for the explanation ! I close this useless issue then !
