### ISSUE TITLE
Extracting m distance in straight skeleton algo

### ISSUE THREAD

**Issue by ThomasCartier** [mthh/sfcgal-rs#4]
Hi,
How do you retrieve the distance in m for each point in the returned result in the function `straight_skeleton_distance_in_m`? I couldn't find my way.
Serializing to wkt enables to get it somehow but it would be better if one could access it numerically.

Thanks

**Comment by mthh** [comment]
Thanks for your feedback. 

In fact, there's currently no way to retrieve the value stored in M, so going through the WKT representation is your only/best option.

But it's a point for improvement, and one for which I can also accept a contribution.

**Comment by ThomasCartier** [comment]
I will dig into it this afternoon! I close for the moment thanks

**Comment by ThomasCartier** [comment]
Hmm, after looking at it, it is more complicated than expected : geotypes (Point and Coord) only have 2d coordinates, so I cannot give a 3d point (the m point) and have it going on.

So right now, and according to my understanding, it is not possible without a major change in the api/structures involved.

Maybe someone can chime in and give me an advice, I am all ears.

Thanks

**Comment by mthh** [comment]
Yes, it is indeed a major (and not so simple) change, which is why I haven't tackled it yet...

I saw that there were various discussions in the georust community (notably in geo / geo-types crates) about trait-based modeling of coordinates using XY, and possibly Z, and possibly M dimensions (I think some good example can be found in the geodesy crate code : https://github.com/busstoptaktik/geodesy/tree/main/src/coordinate).

I've been following these discussions, but haven't yet taken the plunge myself.
However, geo-types don't support points / coordinates with 3 dimensions (Z) and this crate does allow you to manipulate them (it's only the conversion to geo-types that isn't possible for coordinates with 3 dimensions), so it should still be possible to add support for the M dimension without waiting for this to be decided on the geo-types side. I'll have a closer look at this in a few weeks' time, as I'm sure I'll have a bit of time to spare then.

**Comment by ThomasCartier** [comment]
Another way to do this in the meantime, would be to use LineString to store the 3 coordinates.
It's ugly, not that efficient because for each point, a line has to be created. But it may work.

At this point, it is simpler to just parse the string, with the involved cost.

I think that it's important to keep in line with geo for so many reasons you already know. I will read what the geo community say on the matter.

Your crate is great BTW, super boulot :)

I close this issue but do not hesitate to reopen it if you want me to help. 
Cheers,
