### ISSUE TITLE
SFCGAL updated to v2.0

### ISSUE THREAD

**Issue by ThomasCartier** [mthh/sfcgal-rs#6]
Hi,

Just a quick note: apparently sfcgal released the v2.0 with many new c api entries and cgal 6.0.

Cheers!

**Comment by mthh** [comment]
Thanks for the heads up! I'll take a look next week to update the bindings.

**Comment by ThomasCartier** [comment]
Hi Matthieu,
Do you want me to update the bindings and make a PR ?
Adding the bindings should be fast but creating all the test may be longer.

Waiting for your opinion, no need to double the work!

**Comment by ThomasCartier** [comment]
From what I gather, Sfcgal-sys doesn't need to be touched at all thanks to the dynamic build.rs.
Do you confirm?

**Comment by mthh** [comment]
Hi Thomas and thanks for your proposal!

The sfcgal-sys code doesn't need to be touched but I think I will need to publish an updated version of the crate because the code produced exports the signature of functions / constants of the C API (see https://mthh.github.io/sfcgal-sys/sfcgal_sys/#functions for example) and I guess SFCGAL 2.0.0 introduces changes in the C API.

~~I'm glad if you contribute the bindings modification to sfcgal-rs but note that I will release the new version of the bindings under the GPL-3.0 license, as expected since it's a work based on SFCGAL itself under the GPL license (I think I've screwed up so far and it wasn't right to release the bindings under the current license). So please note that you will be contributing code under this new license.~~

Edit: my bad, I just saw that sfcgal is licensed under LGPL-2.0, I don't think writing the bindings (since it's linking dynamically to SFCGAL) in the current license is actually a problem... Please let me know if you have any knowledge on the subject!

**Comment by ThomasCartier** [comment]
I can't talk for the licence legal right now (not enough knowledge), but for the code, I just blamed the c [api h and c files](https://gitlab.com/sfcgal/SFCGAL/-/tree/master/src/capi?ref_type=heads) and it looks stable. 

It looks like they cared to make the api as stable as possible.

Your enums and already existing functions are still up to date but I may have overlooked something.

I will try today, this update brings so many useful features!

**Comment by mthh** [comment]
From the git blame it looks like there is a few new functions exported that could be useful such as `sfcgal_solid_set_exterior_shell`, `sfcgal_geometry_straight_skeleton_partition`, `sfcgal_geometry_buffer3d`, `sfcgal_geometry_scale`, etc.

**Comment by ThomasCartier** [comment]
I will add them all :)

**Comment by mthh** [comment]
Great :)
But it also means releasing a new version of sfcgal-sys.
So I'm in the process of building SFCGAL 2.0.0 in order to publish (probably in about 1 hour) a new version of sfcgal-sys based on 2.0.0 because you will need it to import the new functions and write their bindings.

**Comment by ThomasCartier** [comment]
Nice!

**Comment by mthh** [comment]
I've published sfcgal-sys v0.8.0: https://mthh.github.io/sfcgal-sys/sfcgal_sys (actually documentation is still in the process of being built) / https://crates.io/crates/sfcgal-sys.

In fact I think it was really necessary anymore, I have overlooked the choices I made for this -sys crate where bindings are always regenerated when compiling (compared to some other -sys crates that generates them and include them in the source tree of the published crate).

**Comment by ThomasCartier** [comment]
I think the function `sfcgal_solid_set_exterior_shell` is missing in your update; 
May you add it later ?

**Comment by mthh** [comment]
It seems it was added in the C API after the release of 2.0.0 on 2024-10-10 (https://gitlab.com/sfcgal/SFCGAL/-/commit/481cce229ba36d2493d413cc1e0a061eb340d95c is from 2024-10-23)

**Comment by ThomasCartier** [comment]
👍

**Comment by mthh** [comment]
Closed by #7
